import type { Metadata } from "next";
import { Rubik, Amatic_SC, Noto_Serif_Hebrew } from 'next/font/google';
import "./globals.css";
import AudioPlayer from "@/components/AudioPlayer"; // Import the AudioPlayer

// Rubik (variable font)
const rubik = Rubik({
  subsets: ['latin', 'hebrew'],
  variable: '--font-rubik',
  display: 'swap',
});

// Amatic SC (non-variable font)
const amaticSC = Amatic_SC({
  weight: ['400', '700'], // Weights from user request
  subsets: ['latin', 'hebrew'],
  variable: '--font-amatic',
  display: 'swap',
});

// Noto Serif Hebrew (variable font)
const notoSerif = Noto_Serif_Hebrew({
  subsets: ['hebrew', 'latin'],
  variable: '--font-noto-serif',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} ${amaticSC.variable} ${notoSerif.variable}`}>
      <body className="antialiased">
        <AudioPlayer /> {/* Add the AudioPlayer component */}
        {children}
      </body>
    </html>
  );
}
